FROM microsoft/aspnetcore-build:2.0.2
WORKDIR /app

COPY Com.Ambassador.Service.Core.Lib/*.csproj ./Com.Ambassador.Service.Core.Lib/
COPY Com.Ambassador.Service.Core.WebApi/*.csproj ./Com.Ambassador.Service.Core.WebApi/
RUN dotnet restore ./Com.Ambassador.Service.Core.WebApi/

COPY Com.Ambassador.Service.Core.Lib/. ./Com.Ambassador.Service.Core.Lib/
COPY Com.Ambassador.Service.Core.WebApi/. ./Com.Ambassador.Service.Core.WebApi/
RUN dotnet publish ./Com.Ambassador.Service.Core.WebApi/ --output /out/ --configuration Release
